### ISSUE TITLE
Kotlin crash 

### ISSUE THREAD

**Issue by giuseppesorce** [Cleveroad/AdaptiveTableLayout#19]
I can't use Kotlin. 
I use thos code in java works but in kotlin crash..

`   mCsvFileDataSource = CsvFileDataSourceImpl(this, null)
      tlPipeline = findViewById<AdaptiveTableLayout>(R.id.tlPipeline)
      mTableAdapter = SampleLinkedTableAdapter(this, mCsvFileDataSource)
      tlPipeline.setAdapter(mTableAdapter)`

**Comment by giuseppesorce** [comment]
i debug and problem is AdaptiveTableLayout interface. It's private and Kotlin cant' get in layout.

**Comment by MohammadRezaei92** [comment]
I have error in kotlin too:
` java.lang.IllegalAccessError: Illegal class access: 'package name' attempting to access 'com.cleveroad.adaptivetablelayout.AdaptiveTableAdapter' (declaration of 'package name' appears in /data/app/package name/split_lib_slice_5_apk.apk)`

**Comment by VadimHalimendikCr** [comment]
First of all thank you for using our library. It be fix in next version.
With best regards Cleveroad team.

**Comment by YStepiuk-DOIT** [comment]
Hey everyone!
This issue is closed, but I'm still facing it in version 1.2.1.
Was it really fixed?
And how can I possibly avoid it?

Thanks

**Comment by vyguera** [comment]
I've fixed it in #41. Just wait to pull request is merged.

**Comment by ali-roozbahani** [comment]
Hi, i have the same problem in my Kotlin application.
`Caused by: java.lang.IllegalAccessError: Illegal class access: 'co.tinab.farazindsp.adapters.utils.adaptiveTable.MyLinkedTableAdapter' attempting to access 'com.cleveroad.adaptivetablelayout.ViewHolder' (declaration of 'co.tinab.farazindsp.adapters.utils.adaptiveTable.MyLinkedTableAdapter' appears in /data/app/co.tinab.farazindsp-T3vDEUwpVgHl557LoKgBvQ==/base.apk!classes2.dex)`

**Comment by vyguera** [comment]
There is a pending pull request that adds support to kotlin and fixes some more bugs. You could try it. https://github.com/Cleveroad/AdaptiveTableLayout/pull/41
